-- MySQL Script generated by MySQL Workbench
-- Tue Dec  3 21:01:32 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Secretaria_Administrativa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Secretaria_Administrativa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Secretaria_Administrativa` DEFAULT CHARACTER SET utf8 COLLATE utf8_esperanto_ci ;
USE `Secretaria_Administrativa` ;

-- -----------------------------------------------------
-- Table `Secretaria_Administrativa`.`docentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Secretaria_Administrativa`.`docentes` (
  `id_docente` INT NOT NULL AUTO_INCREMENT,
  `primer_nombre` VARCHAR(20) NOT NULL,
  `segundo_nombre` VARCHAR(20) NULL,
  `primer_apellido` VARCHAR(20) NOT NULL,
  `segundo_apellido` VARCHAR(20) NULL,
  `cedula` VARCHAR(15) NOT NULL,
  `fecha_nac` DATE NULL,
  `estado_civil` VARCHAR(10) NULL,
  `tipo_sangre` VARCHAR(3) NULL,
  `telefono_casa` INT(8) NULL,
  `celular` INT(8) NULL,
  `provincia_res` VARCHAR(15) NULL,
  `distrito_res` VARCHAR(20) NULL,
  `corregimiento_res` VARCHAR(20) NULL,
  `direccion_especif` VARCHAR(100) NULL,
  `categoria_doc` VARCHAR(10) NULL,
  `ubicacion_sede` VARCHAR(15) NULL,
  `depto` VARCHAR(45) NULL,
  `correo` VARCHAR(40) NOT NULL,
  `genero` VARCHAR(10) NULL,
  PRIMARY KEY (`id_docente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Secretaria_Administrativa`.`familiar_doc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Secretaria_Administrativa`.`familiar_doc` (
  `id_familiar` INT NOT NULL AUTO_INCREMENT,
  `parentezco` VARCHAR(15) NOT NULL,
  `nombre_fam` VARCHAR(20) NOT NULL,
  `apellido_fam` VARCHAR(20) NOT NULL,
  `fecha_nac_fam` DATE NOT NULL,
  `localizar` TINYINT NOT NULL,
  `prioridad` INT(2) NOT NULL,
  `telef_casa_fam` VARCHAR(8) NOT NULL,
  `telef_ofi_fam` VARCHAR(8) NULL,
  `celular_fam` VARCHAR(8) NOT NULL,
  `correo_fam` VARCHAR(40) NOT NULL,
  `docentes_id_docente` INT NOT NULL,
  PRIMARY KEY (`id_familiar`),
  INDEX `fk_familiar_doc_docentes1_idx` (`docentes_id_docente` ASC) VISIBLE,
  CONSTRAINT `fk_familiar_doc_docentes1`
    FOREIGN KEY (`docentes_id_docente`)
    REFERENCES `Secretaria_Administrativa`.`docentes` (`id_docente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Secretaria_Administrativa`.`preparacion_academica_doc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Secretaria_Administrativa`.`preparacion_academica_doc` (
  `id_preparacion` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `anio` INT(4) NOT NULL,
  `universidad` VARCHAR(45) NOT NULL,
  `nivel` VARCHAR(15) NOT NULL,
  `docentes_id_docente` INT NOT NULL,
  PRIMARY KEY (`id_preparacion`),
  INDEX `fk_preparacion_academica_doc_docentes1_idx` (`docentes_id_docente` ASC) VISIBLE,
  CONSTRAINT `fk_preparacion_academica_doc_docentes1`
    FOREIGN KEY (`docentes_id_docente`)
    REFERENCES `Secretaria_Administrativa`.`docentes` (`id_docente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Secretaria_Administrativa`.`capacitaciones_doc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Secretaria_Administrativa`.`capacitaciones_doc` (
  `id_capacitaciones` INT NOT NULL AUTO_INCREMENT,
  `nombre_capac` VARCHAR(25) NOT NULL,
  `horas` INT(3) NOT NULL,
  `tipo_participacion` VARCHAR(15) NOT NULL,
  `anio` INT(4) NOT NULL,
  `docentes_id_docente` INT NOT NULL,
  PRIMARY KEY (`id_capacitaciones`),
  INDEX `fk_capacitaciones_doc_docentes1_idx` (`docentes_id_docente` ASC) VISIBLE,
  CONSTRAINT `fk_capacitaciones_doc_docentes1`
    FOREIGN KEY (`docentes_id_docente`)
    REFERENCES `Secretaria_Administrativa`.`docentes` (`id_docente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Secretaria_Administrativa`.`administrativos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Secretaria_Administrativa`.`administrativos` (
  `id_administrativos` INT NOT NULL AUTO_INCREMENT,
  `primer_nombre` VARCHAR(20) NOT NULL,
  `segundo_nombre` VARCHAR(20) NULL,
  `primer_apellido` VARCHAR(20) NOT NULL,
  `segundo_apellido` VARCHAR(20) NULL,
  `cedula` VARCHAR(15) NOT NULL,
  `fecha_nac` DATE NULL,
  `estado_civil` VARCHAR(10) NULL,
  `tipo_sangre` VARCHAR(3) NULL,
  `telefono_casa` INT(8) NULL,
  `celular` INT(8) NULL,
  `provincia_res` VARCHAR(15) NULL,
  `distrito_res` VARCHAR(20) NULL,
  `corregimiento_res` VARCHAR(20) NULL,
  `direccion_especif` VARCHAR(100) NULL,
  `categoria_adm` VARCHAR(10) NULL,
  `ubicacion_sede` VARCHAR(15) NULL,
  `depto` VARCHAR(45) NULL,
  `correo` VARCHAR(40) NOT NULL,
  `genero` VARCHAR(10) NULL,
  PRIMARY KEY (`id_administrativos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Secretaria_Administrativa`.`capacitaciones_adm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Secretaria_Administrativa`.`capacitaciones_adm` (
  `id_capacitaciones` INT NOT NULL AUTO_INCREMENT,
  `nombre_capac` VARCHAR(25) NOT NULL,
  `horas` INT(3) NOT NULL,
  `tipo_participacion` VARCHAR(15) NOT NULL,
  `anio` INT(4) NOT NULL,
  `administrativos_id_administrativos` INT NOT NULL,
  PRIMARY KEY (`id_capacitaciones`),
  INDEX `fk_capacitaciones_adm_administrativos1_idx` (`administrativos_id_administrativos` ASC) VISIBLE,
  CONSTRAINT `fk_capacitaciones_adm_administrativos1`
    FOREIGN KEY (`administrativos_id_administrativos`)
    REFERENCES `Secretaria_Administrativa`.`administrativos` (`id_administrativos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Secretaria_Administrativa`.`preparacion_academica_adm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Secretaria_Administrativa`.`preparacion_academica_adm` (
  `id_preparacion` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `anio` INT(4) NOT NULL,
  `universidad` VARCHAR(45) NOT NULL,
  `nivel` VARCHAR(15) NOT NULL,
  `administrativos_id_administrativos` INT NOT NULL,
  PRIMARY KEY (`id_preparacion`),
  INDEX `fk_preparacion_academica_adm_administrativos1_idx` (`administrativos_id_administrativos` ASC) VISIBLE,
  CONSTRAINT `fk_preparacion_academica_adm_administrativos1`
    FOREIGN KEY (`administrativos_id_administrativos`)
    REFERENCES `Secretaria_Administrativa`.`administrativos` (`id_administrativos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Secretaria_Administrativa`.`familiar_adm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Secretaria_Administrativa`.`familiar_adm` (
  `id_familiar` INT NOT NULL AUTO_INCREMENT,
  `parentezco` VARCHAR(15) NOT NULL,
  `nombre_fam` VARCHAR(20) NOT NULL,
  `apellido_fam` VARCHAR(20) NOT NULL,
  `fecha_nac_fam` DATE NOT NULL,
  `localizar` TINYINT NOT NULL,
  `prioridad` INT(2) NOT NULL,
  `telef_casa_fam` VARCHAR(8) NOT NULL,
  `telef_ofi_fam` VARCHAR(8) NULL,
  `celular_fam` VARCHAR(8) NOT NULL,
  `correo_fam` VARCHAR(40) NOT NULL,
  `administrativos_id_administrativos` INT NOT NULL,
  PRIMARY KEY (`id_familiar`),
  INDEX `fk_familiar_adm_administrativos1_idx` (`administrativos_id_administrativos` ASC) VISIBLE,
  CONSTRAINT `fk_familiar_adm_administrativos1`
    FOREIGN KEY (`administrativos_id_administrativos`)
    REFERENCES `Secretaria_Administrativa`.`administrativos` (`id_administrativos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
