-- MySQL Script generated by MySQL Workbench
-- Mon Nov 18 21:19:38 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Secretaria_Administrativa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Secretaria_Administrativa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Secretaria_Administrativa` DEFAULT CHARACTER SET utf8 COLLATE utf8_esperanto_ci ;
USE `Secretaria_Administrativa` ;

-- -----------------------------------------------------
-- Table `Secretaria_Administrativa`.`docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Secretaria_Administrativa`.`docente` (
  `id_docente` INT NOT NULL AUTO_INCREMENT,
  `primer_nombre` VARCHAR(20) NOT NULL,
  `segundo_nombre` VARCHAR(20) NULL,
  `primer_apellido` VARCHAR(20) NOT NULL,
  `segundo_apellido` VARCHAR(20) NULL,
  `cedula` VARCHAR(15) NOT NULL,
  `fecha_nac` DATE NOT NULL,
  `estado_civil` VARCHAR(10) NOT NULL,
  `tipo_sangre` VARCHAR(3) NOT NULL,
  `telefono_casa` INT(8) NOT NULL,
  `celular` INT(8) NOT NULL,
  `provincia_res` VARCHAR(15) NOT NULL,
  `distrito_res` VARCHAR(20) NOT NULL,
  `corregimiento_res` VARCHAR(20) NOT NULL,
  `direccion_especif` VARCHAR(100) NOT NULL,
  `categoria_doc` VARCHAR(10) NOT NULL,
  `ubicacion_sede` VARCHAR(15) NOT NULL,
  `depto` VARCHAR(45) NOT NULL,
  `cargo_adm` VARCHAR(75) NULL,
  `cargo_gob` VARCHAR(75) NULL,
  `correo` VARCHAR(40) NOT NULL,
  `genero` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_docente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Secretaria_Administrativa`.`familiar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Secretaria_Administrativa`.`familiar` (
  `id_familiar` INT NOT NULL AUTO_INCREMENT,
  `parentezco` VARCHAR(15) NOT NULL,
  `nombre_fam` VARCHAR(20) NOT NULL,
  `apellido_fam` VARCHAR(20) NOT NULL,
  `fecha_nac_fam` DATE NOT NULL,
  `localizar` TINYINT NOT NULL,
  `prioridad` INT(2) NOT NULL,
  `telef_casa_fam` VARCHAR(8) NOT NULL,
  `telef_ofi_fam` VARCHAR(8) NULL,
  `celular_fam` VARCHAR(8) NOT NULL,
  `correo_fam` VARCHAR(40) NULL,
  `docente_id_docente` INT NOT NULL,
  PRIMARY KEY (`id_familiar`, `docente_id_docente`),
  INDEX `fk_familiar_docente_idx` (`docente_id_docente` ASC) VISIBLE,
  CONSTRAINT `fk_familiar_docente`
    FOREIGN KEY (`docente_id_docente`)
    REFERENCES `Secretaria_Administrativa`.`docente` (`id_docente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Secretaria_Administrativa`.`preparacion_academica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Secretaria_Administrativa`.`preparacion_academica` (
  `id_preparacion` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `anio` INT(4) NOT NULL,
  `universidad` VARCHAR(45) NOT NULL,
  `nivel` VARCHAR(15) NOT NULL,
  `docente_id_docente` INT NOT NULL,
  PRIMARY KEY (`id_preparacion`, `docente_id_docente`),
  INDEX `fk_preparacion_academica_docente1_idx` (`docente_id_docente` ASC) VISIBLE,
  CONSTRAINT `fk_preparacion_academica_docente1`
    FOREIGN KEY (`docente_id_docente`)
    REFERENCES `Secretaria_Administrativa`.`docente` (`id_docente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Secretaria_Administrativa`.`capacitaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Secretaria_Administrativa`.`capacitaciones` (
  `id_capacitaciones` INT NOT NULL AUTO_INCREMENT,
  `nombre_capac` VARCHAR(25) NOT NULL,
  `horas` INT(3) NOT NULL,
  `tipo_participacion` VARCHAR(15) NOT NULL,
  `anio` INT(4) NOT NULL,
  `docente_id_docente` INT NOT NULL,
  PRIMARY KEY (`id_capacitaciones`, `docente_id_docente`),
  INDEX `fk_capacitaciones_docente1_idx` (`docente_id_docente` ASC) VISIBLE,
  CONSTRAINT `fk_capacitaciones_docente1`
    FOREIGN KEY (`docente_id_docente`)
    REFERENCES `Secretaria_Administrativa`.`docente` (`id_docente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
